# Model Parameters
model_params: {
    model_config: {
        name: "GaussianModel",
        kwargs: {}
    },
    sh_degree: 3,
    source_path: "data/matrix_city/aerial/train/block_all",
    partition_name: "g2_overlap25_smoke",
    pretrain_path: "output/mc_small_aerial_coarse_smoke/point_cloud/iteration_10",
    model_path: "",
    images: "images",
    block_dim: [2, 2, 1],
    aabb: [-3.5, -4, -10, 4.5, 2, 10],
    num_threshold: 2000,
    ssim_threshold: 0.05,
    resolution: -1,
    white_background: False,
    data_device: "cuda",
    eval: False,
    save_block_only: True,
    overlap_ratio: 0.25,
    overlap_freeze: True,
    freeze_after_iter: 20,
    blend_mode: "soft",
    prune_duplicates: True,
    duplicate_threshold: 0.02,
}

# Pipeline Parameters
pipeline_params: {
    convert_SHs_python: False,
    compute_cov3D_python: False,
    debug: False
}

# Optimization Parameters
optim_params: {
    iterations: 100,
    position_lr_init: 0.000064,
    position_lr_final: 0.00000064,
    position_lr_delay_mult: 0.01,
    position_lr_max_steps: 100,
    feature_lr: 0.0025,
    opacity_lr: 0.05,
    scaling_lr: 0.004,
    rotation_lr: 0.001,
    percent_dense: 0.01,
    lambda_dssim: 0.2,
    densification_interval: 20,
    opacity_reset_interval: 100,
    densify_from_iter: 20,
    densify_until_iter: 50,
    densify_grad_threshold: 0.0002
}
