# Model Parameters
model_params: {
    model_config: {
        name: "GaussianModel",
        kwargs: {}
    },
    sh_degree: 3,
    source_path: "data/scene_1280_5994",
    partition_name: "scene_1280_5994_citygs_smoke",
    pretrain_path: "output/scene_1280_5994_coarse/point_cloud/iteration_30000",
    model_path: "",
    images: "images",
    block_dim: [1, 1, 1],
    aabb: [-3.5, -5.0, -12.0, 3.5, 4.0, 10.0],
    num_threshold: 1000,
    ssim_threshold: 0.05,
    resolution: 8,
    white_background: False,
    data_device: "cuda",
    eval: False,
    save_block_only: True,
}

# Pipeline Parameters
pipeline_params: {
    convert_SHs_python: False,
    compute_cov3D_python: False,
    debug: False
}

# Optimization Parameters
optim_params: {
    iterations: 30000,
    position_lr_init: 0.000064,
    position_lr_final: 0.00000064,
    position_lr_delay_mult: 0.01,
    position_lr_max_steps: 30000,
    feature_lr: 0.0025,
    opacity_lr: 0.05,
    scaling_lr: 0.004,
    rotation_lr: 0.001,
    percent_dense: 0.01,
    lambda_dssim: 0.2,
    densification_interval: 100,
    opacity_reset_interval: 3000,
    densify_from_iter: 500,
    densify_until_iter: 10,
    densify_grad_threshold: 0.0002
}
